### ISSUE TITLE
MacOS 11 Big Sur needed

### ISSUE THREAD

**Issue by arusa** [xiaket/aws-extend-switch-roles-safari#1]
I have already installed xcode 12.1, but it seems I would need MacOS 11 Beta to build the extension.

For Example SFExtensionMessageKey does only exist on MacOS 11...

Maybe we could make it work for Catalina or maybe I just have to wait for Big Sur release.

**Comment by xiaket** [comment]
Thanks for your interest in this project. Indeed this requires macos 11 and I've built it in an earlier beta release.

If you feel you can trust a stranger, please drop me an email: kaix@fastmail.com, and I'll be happy to mail my build to you, and hopefully that will work.

Thanks again!

**Comment by arusa** [comment]
Thanks for the quick reply! I will take a look later if I can solve and build it on Catalina.
And thanks for adapting the plugin for Safari! I wanted to give it a try myself, but found your project 👍

**Comment by xiaket** [comment]
With the release of the Big Sur, I'll close this one as this is no longer a hard-to-achieve thing. Please let me know if I can assist you in any way. :)
